export const GET_BRAND_REQUEST = "GET_BRAND_REQUEST";
export const GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS";
export const GET_BRAND_FAILD = "GET_BRAND_FAILD";

export const CREATE_BRAND_REQUEST = "CREATE_BRAND_REQUEST";
export const CREATE_BRAND_SUCCESS = "CREATE_BRAND_SUCCESS";
export const CREATE_BRAND_FAILED = "CREATE_BRAND_FAILED";

export const DELETE_BRAND_REQUEST = "DELETE_BRAND_REQUEST"; 
export const DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS"; 
export const DELETE_BRAND_FAILED = "DELETE_BRAND_FAILED"; 

export const BRAND_STATUS_SUCCESS = "BRAND_STATUS_SUCCESS";

export const GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS"; 
export const GET_TAGS_FAILED = "GET_TAGS_FAILED";

export const CREATE_TAG_SUCCESS = "CREATE_TAG_SUCCESS";
export const CREATE_TAG_FAILED = "CREATE_TAG_FAILED";

export const DELETE_TAG_SUCCESS = "DELETE_TAG_SUCCESS";
export const DELETE_TAG_FAILED = "DELETE_TAG_FAILED";

export const TAG_STATUS_SUCCESS = "TAG_STATUS_SUCCESS"; 

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED";

export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS" 
export const CATEGORY_CREATE_FAILED = "CATEGORY_CREATE_FAILED" 
